{% set name = "intake-xarray" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 163ca7aa2206ab43468f962c8c3260a2ef1e4bea388ca3d42c427d9b6b3ce133
  patches:
    # Code uses configparser.SafeConfigParser() which was removed in Python 3.12+
    - patches/0001-fix-py-311-configparser.patch  # [py>311]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - intake >=2
    - xarray >=02022
    - zarr
    - dask >=2.2
    - netcdf4
    - fsspec>2022
    - msgpack-python
    - requests

# E   ModuleNotFoundError: No module named 'gcsfs'
{% set deselect_tests = " --deselect=test_network.py::test_open_netcdf_gs" %}
# E   ModuleNotFoundError: No module named 'pydap'
{% set deselect_tests = deselect_tests + " --deselect=test_intake_xarray.py::test_read_opendap_with_auth_netcdf4" %}
# E   FileNotFoundError: [Errno 2] No such file or directory: example_1.nc
{% set deselect_tests = deselect_tests + " --deselect=test_intake_xarray.py::test_to_dask" %}
{% set deselect_tests = deselect_tests + " --deselect=test_intake_xarray.py::test_read" %}
{% set deselect_tests = deselect_tests + " --deselect=test_intake_xarray.py::test_cached_list_netcdf" %}
{% set deselect_tests = deselect_tests + " --deselect=test_catalog.py::test_import_error" %}
{% set deselect_tests = deselect_tests + " --deselect=test_catalog.py::test_catalog" %}
# Needs authentification to the aws s3 bucket
{% set deselect_tests = deselect_tests + " --deselect=test_network.py::test_open_rasterio_s3" %}
test:
  source_files:
    - examples
  imports:
    - intake_xarray
    - intake_xarray.base
    - intake_xarray.image
    - intake_xarray.netcdf
    - intake_xarray.xzarr
  commands:
    - pip check
    - pytest --pyargs intake_xarray.tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - scipy

about:
  home: https://github.com/intake/intake-xarray
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: xarray plugins for Intake
  description:
    This package enables the set of data-loading methods from Xarray to be used within the Intake data access and cataloging system.
  doc_url: https://intake-xarray.readthedocs.io
  dev_url: https://github.com/intake/intake-xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jsignell
    - martindurant
