{% set name = "intake-xarray" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 919b21be9d836bd915cb50f0ac8027b97c69ac2f906b5a3ad7ba045541be7589

build:
  number: 0
  # intake, zarr, namcodecs, and python-snappy currently aren't available on s390x
  # xarray and zarr are available only for py>=3.8
  skip: True  # [py<38]
  script:
    - cp {{ RECIPE_DIR }}/versioneer.py {{ SRC_DIR }}/
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - dask-core >=2.2
    - fsspec >=2022
    - intake >=0.6.6
    - msgpack-python
    - netcdf4
    - requests
    - xarray >=2022
    - zarr

test:
  imports:
    - intake_xarray
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/intake/intake-xarray
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: xarray plugins for Intake
  description:
    This package enables the set of data-loading methods from Xarray to be used within the Intake data access and cataloging system.
  doc_url: https://intake-xarray.readthedocs.io/
  dev_url: https://github.com/intake/intake-xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jsignell
    - martindurant
