travis:
  secure:
    BINSTAR_TOKEN: BHb4swJb/FMgJ14s5uCzpCaYCj6czpXuccehvMdqrbDZY7th+9a7jjBQNQsCfroP0LVGFevGr7Vp6cuImQkWOSVizFQ3cz/6deCTgnracOKDsJuilQcwDR2PgktsLE2N7y6grk8or1lmzuyIASzZO2pAGVCaKu5NUujRd6gVaPdTKxknyiEo7+IvMtRp3JOJRhGv7sD7v+78MUp2iJUcGgoSNDBhShGbAIIsj6OarfL8xpKUT44o4dUKnSVkjYWllPTfNrgpc3b2LjvGZN9lZZtS7jPRDncQcILK39dHBlIQVvs+kbdGTYzCiJpHNHBDS1W4vJ0U2GirzUPhJZzMoRPgccFueSC8jpPr3IlMmqnNOSQsiRwo8R6KhonLl37HUpsgVdlBnVgcAGH23DIxaB/BerY9s9SlotlMAZa09ErMWQqcMr9WeRh1UnzS6qOL+uXdB4aiDjooaZqSM/b0h8xnvzA5shTD2Dk4jC0uNSuUo4DAhk/AXn/0VYA2JbyZCR9wrBqvAM6ptYy5XpcTYqtqfXWrEuO4JrGUwImB5YyYWd46IiGt/1jJ84yyiIaD+jWqPnYL/gwu1kgpsh7cYb0oKQQ442IPThnnGmLvyIDK/1kbadIl06znOMZqg12c1Ef6T0C4aal4AjHUiMcLG2UffNLKCBOHqrVhCR3NOfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
